///*
//* This header is generated by classdump-dyld 1.0
//* on Friday, January 21, 2022 at 8:57:55 AM Pacific Standard Time
//* Operating System: Version 15.2.1 (Build 19C63)
//* Image Source: /System/Library/PrivateFrameworks/ControlCenterServices.framework/ControlCenterServices
//* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
//*/
//
//
//@protocol OS_dispatch_queue, OS_dispatch_source;
//@class NSObject, NSHashTable, NSArray;
//
//@interface CCSModuleSettingsProvider : NSObject {
//
////    NSObject*<OS_dispatch_queue> _queue;
////    NSObject*<OS_dispatch_queue> _callOutQueue;
////    NSObject*<OS_dispatch_source> _configurationChangedSource;
//    NSHashTable* _observers;
//    NSArray* _orderedFixedModuleIdentifiers;
//    NSArray* _orderedUserEnabledModuleIdentifiers;
//    NSArray* _orderedUserEnabledFixedModuleIdentifiers;
//    NSArray* _userDisabledModuleIdentifiers;
//}
//@property (nonatomic,copy,readonly) NSArray * orderedFixedModuleIdentifiers;
//@property (nonatomic,copy,readonly) NSArray * orderedUserEnabledModuleIdentifiers;
//@property (nonatomic,copy,readonly) NSArray * orderedUserEnabledFixedModuleIdentifiers;
//@property (nonatomic,copy,readonly) NSArray * userDisabledModuleIdentifiers;
//+(void)initialize;
//+(id)sharedProvider;
//+(id)_configurationFileURL;
//+(id)_defaultFixedModuleIdentifiers;
//+(id)_configurationDirectoryURL;
//+(id)_readSettings;
//+(id)_defaultUserEnabledFixedModuleIdentifiers;
//+(id)_defaultUserEnabledModuleIdentifiers;
//+(void)_writeOrderedIdentifiers:(id)arg1 userEnabledFixedIdentifiers:(id)arg2 userDisabledIdentifiers:(id)arg3 ;
//+(id)_defaultEnabledModuleOrder;
//-(NSArray *)orderedUserEnabledModuleIdentifiers;
//-(void)addObserver:(id)arg1 ;
//-(void)removeObserver:(id)arg1 ;
//-(NSArray *)userDisabledModuleIdentifiers;
//-(void)_queue_sendConfigurationFileUpdateMessageToObservers;
//-(void)_queue_loadSettings;
//-(void)_queue_startMonitoringConfigurationUpdates;
//-(id)init;
//-(void)_queue_runBlockOnListeners:(/*^block*/id)arg1 ;
//-(void)_queue_stopMonitoringConfigurationUpdates;
//-(NSArray *)orderedUserEnabledFixedModuleIdentifiers;
//-(void)_queue_saveSettings;
//-(void)dealloc;
//-(NSArray *)orderedFixedModuleIdentifiers;
//-(void)setAndSaveOrderedUserEnabledFixedModuleIdentifiers:(id)arg1 ;
//-(void)_queue_handleConfigurationFileUpdate;
//-(void)setAndSaveOrderedUserEnabledModuleIdentifiers:(id)arg1 ;
//@end
